#!/bin/bash
echo "**********************"
echo "* done capture"
echo "**********************"
NAME=$(date +"%Y%m%dT%H%M%S")
ffmpeg -f rawvideo -pixel_format yuv420p -s 640x480 -i 1frame.yuv -vframes 1 ~/Pictures/$NAME.jpg
cp ~/Pictures/$NAME.jpg second.jpg

rm 1frame.yuv
